pages/docs/models.md
pages/docs/preload.md

Fix auto preloading

---

pages/docs/belongs_to.md

relationship was written wrongly so i just corrected it , the typo is in line 29 `in the belongs` to section

typing typo

---

pages/docs/associations.md

Few missing words and wrong tense used. Plural vs singular.

Minor English errors corrected

---

pages/docs/conventions.md

It doesn't require `UpdatedAt` field for Soft Delete but `DeletedAt` field.

Fix conventions.md

---

pages/de_DE/docs/hooks.md
pages/docs/hooks.md
pages/es_ES/docs/hooks.md
pages/id_ID/docs/hooks.md
pages/it_IT/docs/hooks.md
pages/ja_JP/docs/hooks.md
pages/zh_CN/docs/hooks.md

I noticed it said "edger" instead of "eager".

Fix spelling of "eager loading"

---

pages/docs/models.md

Came across this page and found the first sentence difficult to read. Made some minor changes.

Fixed typos

---

pages/docs/connecting_to_the_database.md

Small spelling fix for the docs.

Fixes spelling `it can running`

---

pages/docs/many_to_many.md

May be the example need more complete.

improve many to many example

---

pages/de_DE/docs/transactions.md
pages/docs/transactions.md
pages/es_ES/docs/transactions.md
pages/fr_FR/docs/transactions.md
pages/id_ID/docs/transactions.md
pages/it_IT/docs/transactions.md
pages/ja_JP/docs/transactions.md
pages/tr_TR/docs/transactions.md
pages/zh_CN/docs/transactions.md

Declared `err` and return this.
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jinzhu/gorm.io/78)

docs(transaction): fixed example code

---

pages/docs/has_many.md

Fixed 'Relatinship' to 'Relationship' and improved readability a bit by splitting a sentence in 2 shorter sentences

Fixed minor typo in documentation

---

pages/docs/database.md

This is helpful with writing applications with TDD and GORM.

Adds note on how to use :memory: for sqlite

---

pages/docs/transactions.md

Fix typo in transactions.md

---

pages/docs/delete.md

maybe people want to do delete records permanently for most times.
I think it's better to make the doc more understandable for permanent delete

change delete doc

---

pages/ja_JP/docs/delete.md

change Misunderstanding japanese comment of 「Unscoped delete」

Delete record permanently with Unscoped

---

pages/_data/languages.yml

Russian translate

---

pages/community.md

mysql atabase mapping tool. Hope  give support and promotion

GORM mysql to golang struct

---

pages/de_DE/docs/method_chaining.md
pages/de_DE/docs/query.md
pages/docs/method_chaining.md
pages/docs/query.md
pages/es_ES/docs/method_chaining.md
pages/es_ES/docs/query.md
pages/fr_FR/docs/method_chaining.md
pages/fr_FR/docs/query.md
pages/id_ID/docs/method_chaining.md
pages/it_IT/docs/method_chaining.md
pages/it_IT/docs/query.md
pages/ja_JP/docs/method_chaining.md
pages/ja_JP/docs/query.md
pages/ko_KR/docs/method_chaining.md
pages/ko_KR/docs/query.md
pages/ru_RU/docs/method_chaining.md
pages/ru_RU/docs/query.md
pages/tr_TR/docs/method_chaining.md
pages/tr_TR/docs/query.md
pages/zh_CN/docs/method_chaining.md
pages/zh_CN/docs/query.md

I fixed `IN` to upper case.
Because `IN` is SQL syntax.

Replace `in` to `IN`

---

pages/docs/hooks.md

Fix typo in hooks.md

---

pages/community.md

i change my github username . so i want to update.

change gormt link url

---

pages/_data/languages.yml

Hi,
This PR add pt-BR to the locales list.

Add pt-BR in languages.yml

---

pages/docs/preload.md

This place has puzzled me for a long time, and there is a sample structure that will make it clearer.

added sample code to help understand

---

pages/docs/associations.md
pages/docs/belongs_to.md
pages/docs/composite_primary_key.md
pages/docs/conventions.md
pages/docs/create.md
pages/docs/dialects.md
pages/docs/error_handling.md
pages/docs/has_many.md
pages/docs/has_one.md
pages/docs/hooks.md
pages/docs/many_to_many.md
pages/docs/method_chaining.md
pages/docs/preload.md
pages/docs/query.md
pages/docs/sql_builder.md
pages/docs/write_plugins.md

Fixed not aligned indents

---

pages/docs/belongs_to.md
pages/docs/connecting_to_the_database.md
pages/docs/conventions.md
pages/docs/error_handling.md
pages/docs/has_many.md
pages/docs/has_one.md
pages/docs/many_to_many.md
pages/docs/migration.md
pages/docs/query.md

Resolved with using a relative path instead of an absolute path.

Fixed an issue where links ignored user's language

---

pages/docs/query.md

Fix sample code for Count()

---

pages/zh_CN/docs/connecting_to_the_database.md

fix  [更多支持的参数] URI has whitespace

fix  [更多支持的参数] URI has whitespace

---

themes/navy/source/css/_partial/base.styl

Fix font size for ios

---

pages/docs/query.md

The original code snippet was wrong，report the following error：
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT AVG(amount) FROM `orders`  WHERE (state = ?)))' at line 1

fix code snippet about SubQuery correctly

---

pages/docs/connecting_to_the_database.md

- grammar fixes
- rearrange first section to make it clear that importing wrapped drivers from `gorm/dialects` is recommended
- replace a few lines about how to use SQLite and MS SQL Server with links to their official documentation

fix grammar and improve clarity

---

pages/docs/belongs_to.md

official docs should be exactly accurate because it'll influence much more people than you thank

UserID's type should be uint that is more precise

---

pages/docs/index.md

fix on line 69: map[string]interface{}{"Price": 200, Code: "F42"} =>> map[string]interface{}{"Price": 200, "Code": "F42"}

fix syntax error

---

pages/docs/advanced_query.md

remove duplication condition

---

pages/docs/scopes.md

- [] Only changed English documents, translations should change with https://translate.gorm.io/
Just fixed a typo nothing big

Fixed for copy paste

---

pages/docs/error_handling.md

- [] Only changed English documents, translations should change with https://translate.gorm.io/

fix check ErrRecordNotFound demo code error

---

themes/navy/languages/en.yml

Fix menu typo

---

pages/docs/write_plugins.md

fix comment on demo

---

pages/docs/models.md

change Scanner link to correct url

change Scanner link to correct url

---

pages/docs/advanced_query.md

fix typo in advanced query

---

themes/navy/layout/partial/after_footer.swig

Using jQuery https

---

pages/docs/associations.md
pages/docs/many_to_many.md

Association tags had typos and I fixed them.

Fix association tags' typos

---

pages/docs/advanced_query.md

Update sql statement generated by count

Update count sql statement

---

pages/community.md

Add links for GIN-VUE-ADMIN

---

pages/community.md

remove open sources example

---

pages/docs/create.md
pages/docs/query.md

CC - Improve documentation for create and query

---

pages/docs/connecting_to_the_database.md
pages/docs/models.md

- improve explanation
- fix naming errors

CC - Improve Getting Started docs

---

pages/docs/v2_release_note.md

Updated typo's on the release notes.

Update v2_release_note.md - Fix release notes typos

---

pages/docs/error_handling.md

* Update error_handling doc to added explicit library name for `ErrRecordNotFound` call

chore: added library name to the function call

---

themes/navy/source/css/_partial/highlight.styl

Fix search popup showed behind the code snippet highlight
Fixed:
I set it the `z-index` to 95 because the algolia wrapper for the search popup is using 100 as its `z-index` (see the `style` attribute of the `<span id="algolia-autocomplete-listbox-0">`)
```html
<div id="search-input-wrap" class="on">
<div id="search-input-icon">
<i class="fa fa-search"></i>
</div>
<span class="algolia-autocomplete algolia-autocomplete-right" style="position: relative; display: inline-block; direction: ltr;">
<input type="search" id="search-input" placeholder="Search documents..." class="ds-input" autocomplete="off" spellcheck="false" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-label="search input" aria-owns="algolia-autocomplete-listbox-0" dir="auto" style="position: relative; …
```

Send Code Highlight Backward Behind Search Popup

---

pages/community.md

I made this library a while back, but decided to open source it just now. I believe it has its place in the related works section.
Would love to have @jinzhu view on my usage of gorm (and possible enhancements?)

Add go-paginate

---

pages/docs/delete.md

Update invalid URL in docs
Updating invalid link in docs due to a typo

Update invalid link in docs

---

pages/docs/connecting_to_the_database.md

add host field to postgres connection

---

pages/docs/create.md

minor fix: missing comma

---

pages/docs/migration.md

Minor textual fixes

---

pages/docs/error_handling.md

Minor fix with ErrRecordNotFound.

Minor fix with ErrRecordNotFound.

---

pages/docs/method_chaining.md
pages/docs/session.md

This PR includes fixes of some minor typos and general improvements of English sentences (grammar and syntax) on the following pages: `method_chaining` and `session`.

Fix minor typos and improve English grammar

---

pages/docs/create.md

Clarify UpdateAll for upsert

---

pages/docs/update.md

change `actived` to `active` to make column name consistent

doc(update.md): consistent `active`

---

pages/community.md

Related with https://github.com/go-gorm/gorm/issues/2230
Add two new open-source projects (see https://github.com/go-gorm/gorm/issues/2230)

Add zapgorm and zapgorm2

---

pages/docs/changelog.md
pages/docs/index.md
pages/index.md

Fix typo "statment" to "statement" on three pages.

Fix "statment" typos

---

pages/docs/v2_release_note.md

Added notes on use of Migrator()
Added documentation with some of the changes between v1 and v2 on the release notes page.

Added to v2_release_note.md

---

pages/docs/create.md

fix a typo - a missing `"` ....
---
does this really work?
I does not get it running, yet.

fix typo in docs/create

---

pages/docs/create.md

Revert "fix typo in docs/create"

---

pages/docs/create.md

Revert "Revert "fix typo in docs/create""

---

pages/docs/query.md

I added a new line of code to create users variables  ，
Because I unable to find creation description in current version about users .
Thanks.

Document how to create users variable

---

pages/docs/method_chaining.md

Fixed incorrect age value in method chaining example

fix: Fixed typo in method chaining

---

pages/community.md

add go-admin links

---

pages/docs/sql_builder.md

Add example of Raw SQL

---

pages/docs/create.md

The current documentation for `Omit`could be misleading, as it states that it will assign a value to the fields omitted; but won't.

Create a record and ignore the values for the fields passed to omit.

---

pages/docs/query.md

Generally rephrased the language to make the documentation more readily understood.
Also fixed various grammatical errors.

Improve language on Query page

---

pages/community.md

commit quick start tutorial video

commit quick start tutorial video

---

pages/docs/update.md

Fix typo #384

---

pages/docs/has_many.md

fixed typo

---

pages/docs/query.md

- Correct example SQL statement.

Correct example SQL Statement

---

pages/contribute.md

I added url link. Because I couldn't understand where I should fork when I wanted to contribute the document.

Added url link

---

pages/docs/scopes.md

typo fix in scopes.md

---

pages/docs/models.md

Fixing typo in models page.
`updaing` -> `updating`

Small typo fix in models.md

---

pages/docs/delete.md
pages/docs/update.md

Fix doc golang syntax error

---

pages/community.md

Add a new link with an article written on Medium that validates GORM as ORM to Golang on a CRUD implementation using SQLite as database on tests.

Share article that validate GORM as ORM to Golang

---

pages/community.md

Add new opensource project lib for projects that use Newrelic as a vendor of telemetry to track queries executed by GORM.

Share lib to allow telemetry queries with Newrelic

---

pages/docs/connecting_to_the_database.md

Two code examples had imports missing, I added them.

Add missing driver imports.

---

pages/docs/query.md

Add a `Joins` usage.
This situation occurred in my work, I think it is very handy and it can make code clean.

Add Join a Derived Table Usage

---

pages/docs/update.md

Update variable in the example of `Change Updating Values` section on the page `Update`.

Change variable in the section `Change Updating Values` to use user instead of s

---

pages/docs/scopes.md

close https://github.com/go-gorm/gorm/issues/5263

doc: fix paginate demo

---

pages/docs/associations.md

This change fixes a typo in the word "primary."

Fixed typo in Associations Delete with Select

---

pages/docs/advanced_query.md

Fixed a typo.
When `FirstOrCreate` is called, `RowsAffected` will be created/updated record's count, so the number in the example should be 1.

Fixed typo in advanced_query.md

---

pages/docs/has_many.md
pages/docs/has_one.md
pages/docs/many_to_many.md

I decided to provide more info about how to preload one-to-one, one-to-many, many-to-many relations because there is not much info about that at the `has many`, `has one` and `many to many` pages
Also i have additional little project with implementing all listed above relations here https://github.com/diabeticMike/gorm-doc/tree/dev

Provide additional description on how to preload one-to-one, one-to-many, many-to-many relations

---

pages/docs/has_one.md

This fixes a typo error, it should be Eager loading not Edger loading. This might mislead someone.
Fixes a typo error

Fixes a typo

---

pages/docs/belongs_to.md

close https://github.com/go-gorm/gorm/issues/5258

doc(belongs_to): add references special scenarios

---

pages/docs/context.md

Only grammatical and wording errors were fixed. New content has not been added so this should not affect translations.

Improved wording in the section on contexts.

---

pages/plugin/opentelemetry.html

feat: add go get for opentelemetry

---

pages/gen/associations.md
pages/gen/clause.md
pages/gen/create.md
pages/gen/dao.md
pages/gen/database_to_structs.md
pages/gen/delete.md
pages/gen/dynamic_sql.md
pages/gen/fields.md
pages/gen/index.md
pages/gen/methods.md
pages/gen/plugins.md
pages/gen/query.md
pages/gen/transaction.md
pages/gen/type_safe_sql.md
pages/gen/update.md

feat: gen docs

---

pages/gen/dynamic_sql.md
pages/gen/type_safe_sql.md

optimize gen dynamic sql cases

optimize gen dynamic sql cases

---

pages/_data/menu.yml
pages/_data/sidebar.yml
pages/gen.html
pages/gen/dao.md
pages/gen/index.md
scripts/helpers.js

feat: gen dao

---

pages/gen/database_to_structs.md
pages/gen/methods.md

feat: add methods for gen doc

---

pages/docs/models.md

This pull request only fixes a few typos / grammar issues

Fix some typos / grammar

---

pages/docs/update.md

This pull request fixed a few grammatical errors

Fix grammatical errors

---

pages/community.md

Add link to deepgorm

---

pages/_data/sidebar.yml
pages/gen/gen_tool.md

feat: add gen tool

---

pages/docs/has_one.md

fix foreign key tag property in has_one.md

fix foreign key tag property in has_one.md

---

pages/docs/query.md

Add some warn content for the "string conditions"
Add some warn content below the content of "string conditions"

Add some warn content below the content of "string conditions"

---

pages/gen/associations.md

feat: err eord

---

pages/docs/session.md

Fix typo from `Gortoutine` to `Goroutine`

---

pages/docs/create.md

Add generated MySQL sql for "Upsert / On Conflict".

Add generated MySQL sql for "Upsert / On Conflict"

---

pages/gen/dao.md

Fixes the missing import in the code example.

fix(gen/dao): add missing go import

---

pages/docs/many_to_many.md

- Changed "setup it " to "set it up"

Updated Grammatical Error In Many to Many Docs

---

pages/docs/query.md

Fix typo (syntax error) on example code

Fix typo in query.md

---

pages/docs/update.md

There is an error in the last two code lines (74 and 77) of the [**Update Select Fields**](https://gorm.io/docs/update.html#Update-Selected-Fields) section, there is a call to the `Update` method when the correct call should be to **`Updates`**:

Update the "Update Selected Fields" section within update.md

---

pages/community.md

docs: update community.md

---

pages/gen/database_to_structs.md

feat: gen diy table name

---

pages/docs/connecting_to_the_database.md

Add the TiDB chapter to the `Connecting to a Database` document to give the user prompts.

feat: add tidb to connect document

---

pages/gen/gen_tool.md
pages/zh_CN/gen/gen_tool.md

docs: update gen_tool.md

---

pages/docs/query.md

feat: support inner join #5583 https://github.com/go-gorm/gorm/pull/5583/files
Mention ability to specify join type

Inner join documentation

---

pages/docs/scopes.md

Optimize pagination: when page < 0, assign page a value of 1

optimize pagination

---

pages/docs/update.md

Add description about Save, see https://github.com/go-gorm/gorm/issues/6108

add description about Save

---

pages/docs/method_chaining.md

fix: Example 2 comment

---

pages/docs/connecting_to_the_database.md

TiDB supported FK feature at `v6.6.0`. Update the document.

TiDB Support Foreign Key at `v6.6.0`

---

pages/docs/delete.md

update batch delete document for https://github.com/go-gorm/gorm/issues/6035

update batch delete.

---

pages/docs/write_plugins.md

Update write plugins code sample documentation by adding context parameter on ValueOf and Set function calls
close https://github.com/go-gorm/gorm.io/issues/654

update field.ValueOf and field.Set func call with context param

---

pages/docs/migration.md

add documentation for migration views, close https://github.com/go-gorm/gorm/issues/6187

add documentation for migration views

---

pages/docs/error_handling.md

Added Translate Error feature docs so developers will be able to use the new Translated Error like  ErrDuplicatedKey.

feat: added error translating docs

---

pages/docs/preload.md

add dosc for embedded preload, see https://github.com/go-gorm/gorm/issues/6226

feat: add dosc for embedded preload

---

pages/docs/preload.md

closes https://github.com/go-gorm/gorm/issues/6226

docs: add nested join doc

---

pages/gen/database_to_structs.md

DIY Page with typo
fix the typo at gen/database_to_structs.md

typo at database_to_structs page

---

pages/gen/query.md

fix(typo): field.NewStirng -> field.NewString

---

pages/community.md

https://github.com/go-gorm/gorm/issues/6279
https://github.com/go-gorm/gorm/issues/5761#issuecomment-1328272803

docs: add link for Oracle

---

pages/gen/database_to_structs.md

feat: data mapping for field

---

pages/gen/dynamic_sql.md
pages/gen/sql_annotation.md

- Fixed two typos in the examples of gen documents.

Fixed typos in examples of gen docs

---

pages/docs/associations.md

add doc for association unscoped. https://github.com/go-gorm/gorm/issues/6305

feat: add doc for association unscoped

---

pages/docs/query.md

Note added if developers use soft deleted fields in the model (gorm.DeletedAt) and try to retrieve object/s which is running a different query than just a select statement. 
Related Issue: https://github.com/go-gorm/gorm/issues/6269

Doc update for retrieving object with gorms specific fields

---

pages/ar_SA/docs/many_to_many.md
pages/az_AZ/docs/many_to_many.md
pages/de_DE/docs/many_to_many.md
pages/es_ES/docs/many_to_many.md
pages/fa_IR/docs/many_to_many.md
pages/fr_FR/docs/many_to_many.md
pages/hi_IN/docs/many_to_many.md
pages/id_ID/docs/many_to_many.md
pages/it_IT/docs/many_to_many.md
pages/ja_JP/docs/many_to_many.md
pages/ko_KR/docs/many_to_many.md
pages/pl_PL/docs/many_to_many.md
pages/pt_BR/docs/many_to_many.md
pages/ru_RU/docs/many_to_many.md
pages/tr_TR/docs/many_to_many.md
pages/zh_CN/docs/many_to_many.md

format sturct field

---

pages/gen/query.md

FirstOrInit or FirstOrCreate by gen

feat: Update query.md,FirstOrInit or FirstOrCreate by gen

---

pages/gen/query.md

GEN support Struct & Map Condition

feat: GEN support Struct & Map Condition

---

pages/community.md

Add Open Sources - Go ORM Hepler Plugin. 
- ORM Code Completion.
- Assisted code completion with @Model annotation.
- Assisted code completion with @Table annotation. 
- SQL to Struct conversion.
- Gorm Struct
- Generic Struct

Add Open Sources - Go ORM Helper Plugin

---

pages/docs/migration.md

Per our discussion with @jinzhu, adding the Atlas integration to help developers with automatic migration planning.

pages/docs: adding official atlas integration

---

pages/docs/connecting_to_the_database.md

fix `connecting_to_the_database` typo

---

pages/docs/create.md

Fixed a grammatical error on the create documentation page

grammar correction splited -> split

---

pages/gen/sql_annotation.md

change "{{for _,user:=range user}}" to "{{for _,user:=range users}}"

fix(doc): user -> users

---

pages/docs/transactions.md

I updated the naming of nested transactions in the code. Changed tx3 to tx2 to improve clarity and consistency.

Refactor nested transaction naming

---

pages/gen/query.md

Fixes a typo in the documentation

fix: Update query.md - fixing typo

---

pages/gen/query.md

At some point "exists" was removed from the DO interface and replaced with a separate standalone method. 
https://github.com/go-gorm/gen/blob/f53462308098236f5c5d29117e37f1c7580a7e2a/do.go#L981-L982
If you try to do it the existing way, it says that the generated interface has no field or method Exists.

Update Exists usage in query.md

---

pages/docs/advanced_query.md
yarn.lock

It elaborates on "Locking" section in "Advanced Query". I felt like the current version wasn't that descriptive so I expanded it a bit. Partially solves https://github.com/go-gorm/gorm/issues/6720

Making "Locking" section in "Advanced Query" more elaborate

---

pages/docs/conventions.md

Fixed a small typo in the `conventions.md` file.

Fixed typo in conventions.md

---

pages/docs/security.md

fix(pages/docs/security.md): return err

---

pages/docs/create.md

add a warn about batch insert with default record in SQLite, 
associated with https://github.com/go-gorm/gorm/issues/6335

feat: add a warn about SQLite default tag

---

pages/gen/database_to_structs.md

Update database_to_structs.md, add example to show gen JSON

---

pages/docs/create.md

fix code typo on batch creating example

fix code typo on batch creating example

---

pages/docs/sharding.md

Fix broken Godoc link for sharding package.

Fix broken Godoc link for sharding package

---

pages/community.md

Add Open Sources - DynamoDB Driver
I made a library to issue PartiQL Statements to DynamoDB with GORM.
I hope @jinzhu, GORM community, and DynamoDB community will love it!
https://github.com/miyamo2/dynmgrm
[PartiQL](https://partiql.org/), a SQL-compatible query language, to select, insert, update, and delete data in Amazon DynamoDB.
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ql-reference.html

Add Open Sources - DynamoDB Driver

---

pages/_data/sidebar.yml
pages/docs/has_many.md
pages/docs/has_one.md
pages/docs/polymorphism.md
themes/navy/languages/en.yml

Enhance polymorphism documentation since change made in https://github.com/go-gorm/gorm/pull/6716 
Add it's own page since it was previously saying things about the compatibility of polymorphism in has-many for has-one.

refacto: add polymorphism informations

---

pages/docs/advanced_query.md

Update advanced_query.md fix a typo

---

pages/community.md

This PR adds `immugorm` driver to the **Open Sources** sections of the community.md file.

Add immugorm to community.md

---

pages/gen/clause.md

Added missing letter to doc for correction

(doc): fixed doc on clauses section

---

pages/docs/models.md

In the first example, earlier gorm.Model was used to depict an embedded struct. For new users like myself, there might be confusion on what gorm.Model exactly is, and why we have done it so. Hence, here, I depict the usage through another struct within the example (structs copied from the example below this one)

Changed the first example in "Embedded Struct"

---

pages/gen/dao.md

The demo code run failed
https://github.com/go-gorm/gorm.io/blob/master/pages/gen/dao.md#configuration
Extra commas should be removed.

Remove commas

---

pages/community.md

I have added GaussDB database driver, welcome everyone to use it.

feat: 增加GaussDB数据库驱动

---

pages/docs/belongs_to.md

Synchronize  the type of CompanyID in User  with the type of CompanyID in Company
Made the type of CompanyID in User and type of CompanyID in Company identical.

Correct  reference type

---

pages/community.md

There wasn't a [DuckDB](https://duckdb.org) driver for Gorm, so I wrote one!
Here is the [driver](https://github.com/alifiroozi80/duckdb). Please take a look at it. Any contributions are greatly appreciated!

feat(community): Add DuckDB driver

---

pages/docs/models.md

Added one example to Table Names convention

---

pages/docs/serializer.md

Add package name so code example works

fix import of schema.Field in code example

---

pages/zh_CN/docs/the_generics_way.md

New translations the_generics_way.md (Chinese Simplified)

---

pages/docs/preload.md

Added some example of Generics API usage in `Preloading (Eager Loading)` document page

add generics api examples for preloading (Eager Loading) document page
