pages/docs/belongs_to.md
pages/docs/conventions.md
pages/docs/has_many.md
pages/docs/many_to_many.md

Fixes typo in multiple locations `priamry` -> `primary`

Fix typo "priamry"

---

themes/navy/source/css/_partial/highlight.styl

Fix sidebar overlaying code blocks

---

themes/navy/layout/partial/after_footer.swig

This allows GORM to be hosted on secure sites (as an example, on https://gorm.app.render.com) without mixed content warnings.

Load jQuery with the same scheme as the including page

---

pages/docs/associations.md

`association_autoupdate` was probably copy pasted from the previous example and not updated.

Fix save_associations example GORM tag

---

pages/docs/has_one.md

This PR for #115 updates the has_one documentation, which is currently using a belongs_to example instead of a has_one example.
It also inverts the order of the types in the example for the example to be usable with local types in a function instead of requiring global scope, making the example more usable;

Issue #115: incorrect examples in has_one documentation.

---

pages/docs/dialects.md

line 59 (at the time) had a mistake: "secretsIsEqual := reflect.DeepEqual(resultDoc.Secrets, resultDoc.Secrets)"
Changed to: "secretsIsEqual := reflect.DeepEqual(resultDoc.Secrets, sampleDoc.Secrets)"

Updated dialects.md

---

pages/docs/composite_primary_key.md

I also consider this a bit unexpected behavior. I think ideally the Gorm should see there are more `primary_key` fields in a struct and turn off `auto_increment` for them automatically. And keep `auto_increment` on by default only for the case when there is a single `primary_key` in the struct.
That may be difficult to implement, though. So as long as the current implementation is kept, the documentation should be there to clarify this behaviour.

Document the issue #1037

---

pages/docs/query.md

Fixed an error. Previous version does a query with an int for a name that is a string. Since I don't think that someone can be called "3" (as int), I fixed it with a real name (mine, just because I'm lazy af).

Fixed an error in Scan code example.

---

pages/docs/dialects.md

Fix `go-vet` warning  `composite literal uses unkeyed fields`

Fix linter warning

---

pages/docs/connecting_to_the_database.md

See: https://github.com/go-gorm/gorm/issues/2875
Otherwise you get one Sqlite database per thread, which in go makes things very surprising. Based on your luck you might get routerd to a thread with some data, and sometimes not with data.

Use shared memory Sqlite database

---

pages/docs/transactions.md

Fixed (what I suspect) is a typo in nested transactions example.
I changed tx to tx2 as per the nested function variable.

Fix typo in nested transactions example

---

pages/docs/associations.md

Append associations will break if it does not use pointer, therefore put an `&` before associated model in the document.

Fix association.md

---

pages/docs/delete.md

Minor fix for documentation that misspell  "primary" with "priamry" .

docs: Fix typo of "primary" word

---

pages/docs/method_chaining.md

Fix typo at method_chaining.md

---

pages/docs/security.md

The string version of `db.Order()` is simply casting the given `value` to string without any SQL escape. https://github.com/go-gorm/gorm/blob/v1.20.12/chainable_api.go#L199 (snippets below)
```
default:
tx.Statement.AddClause(clause.OrderBy{
Columns: []clause.OrderByColumn{{
Column: clause.Column{Name: fmt.Sprint(value), Raw: true},
}},
})
}
```
This patch adds a note about this behaviour.
Sample code to produce the issue:
```
r := struct{}{}
db, _ := gorm.Open(sqlite.Open(filepath.Join(os.TempDir(), "gorm.db")), &gorm.Config{})
dryDB := db.Session(&gorm.Session{DryRun: true})
result := dryDB.Order("name; drop table users;").Find(&r)
fmt.Println(result.Statement.SQL.String())
// Output: SELECT * FROM `` ORDER BY name; drop table users;
```
If the order field is an untrusted user input, it …

Mark the string argument of db.Order() as unsafe

---

pages/docs/constraints.md

line 34, you say "`OnDelete`" twice
This fix a syntax error on line 34 of pages/docs/constraints.md, you say "`OnDelete`" twice

Fix a syntax error

---

pages/docs/data_types.md

The link to the `Scanner` interface currently results in a 404. This PR sets the proper URL to the interface.

fix link to scanner interface

---

pages/docs/v2_release_note.md

Slow SQL threshold value is incorrect (outdated) in the doc - the threshold is now 200ms.
https://github.com/go-gorm/gorm/blob/master/logger/logger.go#L63

Incorrect slow SQL time for logger in release notes

---

pages/docs/belongs_to.md

I spent an embarrassing amount of time trying to figure out why my models were not deriving relationships. This addendum to the documentation would have helped me, so I offer it to help others.
It emphasizes the importance of having the `CompanyID` as well as `Company` struct attributes, and helps set the stage for the rest of the documentation.

Add details to belongs to

---

pages/docs/logger.md

Mirror the changes from go-gorm/gorm#4450
I found it hard to understand what the `fc` argument was for in the `logger.Interface` type, so I added return value names.

Added return names to logger.Interface.Trace

---

pages/docs/delete.md

Fixed a typo [here](https://gorm.io/docs/delete.html#Batch-Delete) (primary was misspelled).

Fix spelling of "primary" for `gorm.DB#Delete()` batch delete

---

pages/docs/many_to_many.md

Fix incorrect example in overriding many_to_many foreign keys. The JoinReferences tag's value is incorrect.

Fix incorrect example in overriding many_to_many foreign keys

---

pages/docs/connecting_to_the_database.md

In connecting to the database with existing database connection example `postgres` driver name is used along with `gorm.io/driver/postgres` driver.
`gorm/driver/postgres` is using `pgx` driver underneath. Pgx registers itself with `pgx` as driver name.
Refer to https://github.com/jackc/pgx/blob/2799739ef37f11909f6c1663cf7e77faf80fb592/stdlib/sql.go#L104
Using current example causes error
> sql: unknown driver "postgres" (forgotten import?)
This PR changes driver name used in example to `pgx`

Connecting to PostgreSQL database with pgx driver

---

pages/docs/v2_release_note.md

Remove the parenthesis at the end of the `&Users{}`
Incorrect
```go
db.Migrator().CreateConstraint(&Users{}), "Profiles")
db.Migrator().CreateConstraint(&Users{}), "fk_users_profiles")
```
Correct
```go
db.Migrator().CreateConstraint(&Users{}, "Profiles")
db.Migrator().CreateConstraint(&Users{}, "fk_users_profiles")
```

Fixed typo in Migrator.CreateConstraint()

---

pages/docs/query.md

I believe this example "Join with conditions" query is meant to use the regular gormDB db.Where, but the docs currently have it using DB.Where
On the other hand, maybe you intended to guide users to use the regular sql db accessible at db.DB(). In that case, it should be made clear in the text preceding this example.
Use the lowercase db to indicate you're using the gormDB `.Where`

Change DB.Where to db.Where

---

pages/docs/connecting_to_the_database.md

The example uses the package, `gorm.io/driver/mysql`, for `mysql.New(...)` and `mysql.Config{}`. I added the import to the docs so that it is clearer that this import is required for the example to work.

Add import for MySQL example

---

pages/community.md

Add an article link to the `GORM Community` page describing how to use strongly typed JSON fields with GORM

Add link to article on strongly typed JSON fields

---

pages/de_DE/404.swig
pages/pt_BR/404.swig

Running `hexo serve` on the current `master` branch results in two errors, the first of which is:
```
reason: 'can not read a block mapping entry; a multiline key may not be an implicit key',
mark: {
name: null,
buffer: 'layout: raw\n' +
'A fantástica biblioteca ORM para Golang, projetada para ser amigável para desenvolvedores.\n' +
'A fantástica biblioteca ORM para Golang\n' +
'comentários: falso\n',
position: 154,
line: 3,
column: 11,
snippet: ' 1 | layout: raw\n' +
' 2 | A fantástica biblioteca ORM para Golang, pr ...\n' +
' 3 | A fantástica biblioteca ORM para Golang\n' +
' 4 | comentários: falso\n' +
'----------------^'
}
}
} Process failed: %s pt_BR/404.swig
```
This is because the yaml for two of the 404 pages was broken. In one case, the keys had been also translated into …

add missing keys to yaml

---

README.md
_config.yml
pages/docs/v2_release_note.md

A number of links in the documentation and config were using `http://` where `https://` is supported. All of these will redirect from http to https, but there's no reason not to just use https directly.

use https instead of http where supported

---

pages/docs/has_one.md

Fix foreign key name in an example for "has one" association

fix foreign key name in has_one.md

---

pages/docs/has_many.md

This pull request fixes the typo in the has-many documentation. The field's name should be `Toys`, not `Toy`, as is declared on [line 109](https://github.com/go-gorm/gorm.io/blob/master/pages/docs/has_many.md?plain=1#L109).

Fix typo in `has_many.md`

---

pages/docs/query.md

This adds an warning to be careful with using db.Find(&user) to retrieve single objects

Add Query using find without a limit should come with a warning

---

themes/navy/layout/partial/footer.swig

In the footer on https://gorm.io/, the Twitter and GitHub icons currently do not look to be rendering correctly, possibly due to a FontAwesome incompatability:
On Firefox these appear as the following:
And on Chromium, they are 'invisible':
I've updated the classes to use the Font Awesome v5 free icon classes, and they now appear to be working on both Firefox and Chromium:

Fix Twitter and github icons

---

pages/docs/create.md

Users may use `Create` and `CreateInBatches` mistakenly. I think we should notice that `CreateInBatches` may cause an (unknown) transaction.
For example, when user want to insert only a few rows (like, 2) of data, they should use `Create(datas)` instead of `CreateInBatches(datas, len(datas))`.
Issue is found and fixed https://github.com/go-gorm/gorm/pull/6174/files . But more example and explaination is preferred

Add detailed example for Create and notice for CreateInBatches

---

pages/gen/associations.md

Documenting use case with preloading associations regardless if they were soft deleted or not. 
Covering base use case of: https://github.com/go-gorm/gen/pull/505

Document including soft deleted records using Preload

---

pages/gen/associations.md

This PR adds 'references' tag to the generated model. When you try to relate to table in database and the resulting generated model doesn't have this tag, it will fail with 'GORM association error: invalid field for struct' error. Adding the tag fixes the error as now GORM is informed explicitly which field to relate to. 
Additionally the PR fixes some typos on the same page.

Add gorm tag to generated model

---

pages/docs/error_handling.md

When error handling, errors like `ErrRecordNotFound` are available only when Dialect Translated Errors are enabled. This section was not obvious when skimming through the docs and it leads to wasted hours and creations of issues like [#4037](https://github.com/go-gorm/gorm/issues/4037). This commit makes it more visible and fixes a few punctuations

Make dialect translated errors more visible

---

pages/docs/dbresolver.md

It fixes a typo in the [DBResolver Documentation](https://gorm.io/docs/dbresolver.html). 
It seems like it should be `db.Clauses` not `DB.Clauses`

Fix the typo in dbresolver.md

---

themes/navy/source/css/_partial/highlight.styl

This change ensures that the content of code blocks remains fully visible and readable when printed, by preventing long lines from disappearing off the edge of the page.
Before:
After:

When printing, wrap lines in code blocks.

---

pages/docs/polymorphism.md

Changed the Dog.Toy relation to []Toy, as per defined in the previous code block. It's a syntax error without the change.

Update polymorphism.md Dog.Toy -> Dog.[]Toy

---

pages/docs/models.md

This is a rather minor change that adds clarification on how to combine multiple tags in a model. It is based on [this code](https://github.com/go-gorm/gorm/blob/4a50b36f638c6899089e6e3457425528ce693933/schema/field.go#L109) for parsing using a semicolon joiner and [this code](https://github.com/go-gorm/gorm/blob/4a50b36f638c6899089e6e3457425528ce693933/schema/utils.go#L16C6-L16C21) for handling escapes within parameters.

Minor clarification on tag format separators

---

pages/docs/has_one.md

Fix has_one example references value

Fix has_one example references value

---

pages/docs/migration.md

Fixed a typo in the Atlast Integration section of the Migration documentation
Closes #777

Fix typo in atlas integration docs

---

pages/docs/models.md

include description that fields must be exported in order to be mapped
`schema.go` doesn't inspect non-exported fields:
https://github.com/go-gorm/gorm/blob/deceebfab8c460cfee229233aded2821ac6b08eb/schema/schema.go#L204
see also https://github.com/go-gorm/gorm/issues/7251

Update models.md to describe that non-exported fields are ignored

---

pages/docs/update.md

I believe the documentation should reflect this behavior because, during heavy usage of `Save`, I unexpectedly encountered cases where `rowEffect=0` triggered record creation. Admittedly, this was also due to my own oversight in considering this edge case.

Update Save description

---

pages/community.md

Added a new "Learning Resources" section to the Community page featuring an interactive learning platform for GORM.
**Changes:**
- Added new section between "Chat" and "Links" sections
- Featured the Go Interview Practice platform which provides:
- Web-based IDE for instant GORM coding (no setup required)
- Progressive challenges covering CRUD operations, associations, migrations, advanced queries, and the new Generics API
- Community leaderboards and real-world scenarios
- Hands-on practice for developers learning GORM
This addresses the community need for practical, interactive learning resources and showcases the new Generics API introduced in GORM v1.30.0+.

Add interactive learning platform to Community page
